### ISSUE TITLE
I've waited long time but...

### ISSUE THREAD

**Issue by omgfrost** [oliverfei/HearthstoneDeckViewer#10]
...why new expac cards are still not visible? 
![BF0acLG 1](https://user-images.githubusercontent.com/14861120/93978664-97a27580-fd7c-11ea-9110-35f7a5d5381d.png)
(hovered over card in the image)
Thanks in advance

**Comment by oliverfei** [comment]
Oh sorry, forgot to redeploy the site. Should be good now. I'll see if I can automate this...
