### ISSUE TITLE
I can't understand why...

### ISSUE THREAD

**Issue by omgfrost** [oliverfei/HearthstoneDeckViewer#13]
...pasting a code like for ex this thijs one:
`AAECAaIHBNnRA/roA/zoA+fwAw2qywOfzQPHzgOk0QOL1QPn3QPz3QP36AP56AOo6wOq6wOr6wP2nwQA`
and click "Add Deck(s)" ,sometimes, is not showing up...
A workaround is to hit tab key and so Add decks highlights up and then click it. And so deck is showing.(But not all the time)
Will be a solution to this?
Thanks in advance
EDIT: once a deck is added, the pasting and clicking add decks is working at once!
So i don't know why, for the first deckcode, i need to do above procedure.

**Comment by oliverfei** [comment]
Hmm, probably has something to do with the logic that enables/disables the "add decks" button. In the meantime, would hitting the "ENTER" key be an ok work around?

**Comment by oliverfei** [comment]
Think I found the issue and pushed a fix. Should work now.
