### ISSUE TITLE
Highlander deckcodes with Custom name don't get shown

### ISSUE THREAD

**Issue by omgfrost** [oliverfei/HearthstoneDeckViewer#7]
Hello,
according to this: [https://github.com/oliverfei/HearthstoneDeckViewer/pull/5](https://github.com/oliverfei/HearthstoneDeckViewer/pull/5)
this format for highlander deckcode with custom name won't work:
```
### EGOWAFFLE HL HUNTER
# Format: Standard
# Year of the Phoenix
#
AAECAR8etQPhBIoHlwjbCfyjA+SkA6alA4SnA4qtA4utA46tA/muA/yvA/6vA4ewA+ewA/+wA4KxA4WxA4exA9iyA6+3A4O5A6K5A/+6A9a+A9e+A96+A8PMAwAA
#
# To use this deck, copy it to your clipboard and create a new deck in Hearthstone
```
I tried also with this format which usually work with non highlander decks:
```
### DECKNAME
#
DECKCODE
#
# To use this deck, copy it to your clipboard and create a new deck in Hearthstone
```
and it also not working with HL deckcodes.
Is it because HL deckcodes are too long or something?
Thanks in advance

**Comment by oliverfei** [comment]
HL deckcode wasn't being extracted as it wasn't recognized by the regex pattern I used for finding base64 strings. I've since updated how the site extracts the deckcode to just take the longest word as a quick fix.

**Comment by oliverfei** [comment]
@omgfrost closing this for now as per my previous comment. Feel free to reopen if you're still having problems with this.
